### ISSUE TITLE
"reopen closed file" moves reopened tab to the right of its previous location

### ISSUE THREAD

**Issue by mykmelez** [facelessuser/TabsExtra#21] opened 2015-01-01 01:01 UTC
I like *fallback_focus* set to `right`, which is why I found and installed TabsExtra! But there's an issue with it: if you "reopen closed file", the reopened tab doesn't go back to its previous position on the tab bar. Instead, it jumps one position to the right.

Steps to Reproduce:

1. Open three tabs, A, B, and C, in that order.
2. Activate tab B (the middle tab) and then close it (Cmd-W on my Mac).
3. Reopen it (Cmd-Shift-T).

B should reopen between A and C, which is where it was before; but instead it reopens to the right of C!

**Comment by facelessuser** [comment] 2015-01-01 06:22
Yeah, I know this is a problem, and this is related to issue #11 and issue #15.  Basically, the tab focus features is an elaborate series of hack that adds this functionality.  It is elaborate because the API just isn't built well for this kind of thing (there are so many quirky exceptions you have to account for).  And because of all the hacks, you get other side effects.  It is on my list to evaluate.  It is possible I may kill the specialized tab focus features all together as, though I like the feature, it has become a whack-a-mole game of fixing one quirk and others popping up.

And because of all this, I haven't yet implemented tab open focus control (which will add more complexity). I haven't yet given up on the feature yet, but it is possible I may throw out the feature all together.  As this issue is already covered in #11 and #15.  I will probably close this issue.

**Comment by mykmelez** [comment] 2015-01-01 19:22
Ok, makes sense, I've subscribed to the other two issues, so I can track any work being done there.

**Comment by facelessuser** [comment] 2015-02-04 19:51
Actually this is a duplicate of #11.

**Closed by facelessuser** 2015-02-04 19:51 UTC
Labels: Duplicate
